-- Запусти цей файл один раз у Supabase → SQL Editor → New Snippet → Run.

create table if not exists public.order_documents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  order_id bigint not null references public.orders(id) on delete cascade,
  type text not null check (type in ('ttn', 'marking', 'invoice')),
  title text not null,
  file_path text not null,
  file_url text,
  unique (order_id, type)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_id bigint references public.products(id) on delete set null,
  order_id bigint references public.orders(id) on delete set null,
  movement_type text not null check (movement_type in ('receipt', 'writeoff', 'sale')),
  quantity integer not null check (quantity > 0),
  note text
);

alter table public.order_documents enable row level security;
alter table public.inventory_movements enable row level security;

drop policy if exists "Admins manage order documents" on public.order_documents;
create policy "Admins manage order documents" on public.order_documents
for all to authenticated using (true) with check (true);

drop policy if exists "Admins manage inventory movements" on public.inventory_movements;
create policy "Admins manage inventory movements" on public.inventory_movements
for all to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('order-documents', 'order-documents', false)
on conflict (id) do update set public = false;

drop policy if exists "Admins manage order document files" on storage.objects;
create policy "Admins manage order document files" on storage.objects
for all to authenticated using (bucket_id = 'order-documents') with check (bucket_id = 'order-documents');

-- Продаж із сайту автоматично списує залишок і створює запис у «Обліку».
create or replace function public.place_order(payload jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order_id bigint;
  line jsonb;
  item_id bigint;
  item_quantity integer;
begin
  for line in select * from jsonb_array_elements(coalesce(payload->'items', '[]'::jsonb)) loop
    item_id := nullif(line->>'id', '')::bigint;
    item_quantity := greatest(1, coalesce(nullif(line->>'quantity', '')::integer, 1));
    if item_id is null then raise exception 'У замовленні немає ID товару.'; end if;
    update public.products
      set stock_quantity = case when stock_quantity is null then null else stock_quantity - item_quantity end,
          in_stock = case when stock_quantity is not null and stock_quantity - item_quantity <= 0 then false else in_stock end
      where id = item_id and (stock_quantity is null or stock_quantity >= item_quantity);
    if not found then raise exception 'Товар уже закінчився або не знайдений.'; end if;
  end loop;

  insert into public.orders (customer_name, phone, email, delivery_method, delivery_details, delivery_data, payment_method, notes, items, total)
  values (payload->>'customer_name', payload->>'phone', nullif(payload->>'email', ''), payload->>'delivery_method', nullif(payload->>'delivery_details', ''), payload->'delivery_data', payload->>'payment_method', nullif(payload->>'notes', ''), coalesce(payload->'items', '[]'::jsonb), coalesce((payload->>'total')::numeric, 0))
  returning id into new_order_id;

  for line in select * from jsonb_array_elements(coalesce(payload->'items', '[]'::jsonb)) loop
    item_id := nullif(line->>'id', '')::bigint;
    item_quantity := greatest(1, coalesce(nullif(line->>'quantity', '')::integer, 1));
    insert into public.inventory_movements (product_id, order_id, movement_type, quantity, note)
    values (item_id, new_order_id, 'sale', item_quantity, 'Продаж із сайту');
  end loop;
  return new_order_id;
end;
$$;

grant execute on function public.place_order(jsonb) to anon, authenticated;
notify pgrst, 'reload schema';
