-- Запустіть один раз у Supabase → SQL Editor.
-- Відгуки з фото та складські залишки.

alter table public.products
  add column if not exists stock_quantity integer check (stock_quantity is null or stock_quantity >= 0);

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_id bigint not null references public.products(id) on delete cascade,
  author_name text not null check (char_length(author_name) between 2 and 80),
  body text not null check (char_length(body) between 2 and 1200),
  rating smallint not null check (rating between 1 and 5),
  photo_url text,
  is_approved boolean not null default false
);

alter table public.product_reviews enable row level security;

drop policy if exists "Public can read approved product reviews" on public.product_reviews;
create policy "Public can read approved product reviews"
on public.product_reviews for select to anon, authenticated
using (is_approved = true);

drop policy if exists "Customers can submit product reviews" on public.product_reviews;
create policy "Customers can submit product reviews"
on public.product_reviews for insert to anon, authenticated
with check (is_approved = false);

drop policy if exists "Admins manage product reviews" on public.product_reviews;
create policy "Admins manage product reviews"
on public.product_reviews for all to authenticated
using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('review-images', 'review-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Customers upload review photos" on storage.objects;
create policy "Customers upload review photos"
on storage.objects for insert to anon, authenticated
with check (bucket_id = 'review-images');

drop policy if exists "Public can read review photos" on storage.objects;
create policy "Public can read review photos"
on storage.objects for select to anon, authenticated
using (bucket_id = 'review-images');

-- Атомарно створює замовлення й списує лише ті залишки,
-- для яких у товарі вказано число. NULL = склад для товару ще не ведеться.
create or replace function public.place_order(payload jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order_id bigint;
  line jsonb;
  item_id bigint;
  item_quantity integer;
begin
  for line in select * from jsonb_array_elements(coalesce(payload->'items', '[]'::jsonb)) loop
    item_id := nullif(line->>'id', '')::bigint;
    item_quantity := greatest(1, coalesce(nullif(line->>'quantity', '')::integer, 1));
    if item_id is null then raise exception 'У замовленні немає ID товару.'; end if;
    update public.products
      set stock_quantity = case when stock_quantity is null then null else stock_quantity - item_quantity end,
          in_stock = case when stock_quantity is not null and stock_quantity - item_quantity <= 0 then false else in_stock end
      where id = item_id and (stock_quantity is null or stock_quantity >= item_quantity);
    if not found then raise exception 'Товар уже закінчився або не знайдений.'; end if;
  end loop;

  insert into public.orders (customer_name, phone, email, delivery_method, delivery_details, delivery_data, payment_method, notes, items, total)
  values (
    payload->>'customer_name', payload->>'phone', nullif(payload->>'email', ''),
    payload->>'delivery_method', nullif(payload->>'delivery_details', ''), payload->'delivery_data',
    payload->>'payment_method', nullif(payload->>'notes', ''), coalesce(payload->'items', '[]'::jsonb),
    coalesce((payload->>'total')::numeric, 0)
  ) returning id into new_order_id;
  return new_order_id;
end;
$$;

grant execute on function public.place_order(jsonb) to anon, authenticated;
